name: cycle

on:    
  pull_request:
    
jobs:
  splitter:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: check and dispatch
      run: |
           STR="2"
           if [ `grep -c "$STR" 0/1` -ne '0' ];
           then
             echo "NEXTEP"
             curl --request PATCH \
             --url ${{ github.event.pull_request.issue_url }} \
             --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
             --data '{"milestone": 2}'
             curl --request PATCH \
             --url ${{ github.event.pull_request.issue_url }} \
             --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
             --data '{"labels": [ "on 1st" ]}'
             curl --request POST \
             --url ${{ github.event.pull_request.issue_url }}/comments \
             --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
             --data '{"body": "You may continue with https://github.com/ojedavidea/eLearning/0/2"}'
           else
             echo "FLIP"
             curl --request PATCH \
             --url ${{ github.event.pull_request.issue_url }} \
             --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
             --data '{"labels": [ "try" ]}'
             curl --request POST \
             --url ${{ github.event.pull_request.issue_url }}/comments \
             --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
             --data '{"body": "You may continue with https://github.com/ojedavidea/eLearning/0/1_1"}'
             exit 1
           fi
