name: splitter_ruche-1.id

on:
  pull_request:
    paths: 
      - 0/1/ruche-1.id

jobs:
  splitter_ruche-1.id_1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dispatcher_ruche-1.id_1_1
      run: |
        line=$(tail -n 2 0/1/ruche-1.id)
        SUB="name: Octocat"
        if grep -q "$SUB" <<< "$line";
        then
           echo "NEXTEP"
           curl --request PATCH \
           --url ${{ github.event.pull_request.issue_url }} \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"milestone": 1}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "first comment 1"}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "second comment 1"}'
        else
           echo "FLIP"
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "minus first comment 1"}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "minus second comment 1"}'
           exit 1
        fi

    - name: Dispatcher_0/1/ruche-1.id_1_2
      run: |
        line=$(tail -n 3 0/1/ruche-1.id)
        SUB="My Name"
        if grep -q "$SUB" <<< "$line";
        then
           echo "NEXTEP"
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "first comment 2"}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "second comment 2"}'
        else
           echo "FLIP"
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "minus first comment 2"}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "minus second comment 2"}'
           exit 1
        fi

  labeler:
    needs: splitter_ruche-1.id_1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          configuration-path: .github/labeler.yml
