name: splitter

on:
  pull_request:
    paths: 
      - 0/1

jobs:
  splitter1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dispatcher 1
      run: |
        line=$(tail -n 2 0/1)
        SUB="name: Octocat"
        if grep -q "$SUB" <<< "$line";
        then
           echo "NEXTEP"
           curl --request PATCH \
           --url ${{ github.event.pull_request.issue_url }} \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"milestone": 1}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }} \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"labels": [ "1" ]}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "/add-labels"}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "second comment"}'
        else
           echo "FLIP"
           curl --request PATCH \
           --url ${{ github.event.pull_request.issue_url }} \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"labels": [ "-1" ]}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "minus first comment"}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "minus second comment"}'
           exit 1
        fi

    - name: Namer 1
      run: |
        line=$(tail -n 3 0/1)
        SUB="My Name"
        if grep -q "$SUB" <<< "$line";
        then
           echo "NEXTEP"
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }} \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"labels": [ "SUB" ]}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "SUB"}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "second comment"}'
        else
           echo "FLIP"
           curl --request PATCH \
           --url ${{ github.event.pull_request.issue_url }} \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"labels": [ "-1" ]}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "minus first comment"}'
           curl --request POST \
           --url ${{ github.event.pull_request.issue_url }}/comments \
           --header 'authorization: token ${{ secrets.GITHUB_TOKEN }}' \
           --data '{"body": "minus second comment"}'
           exit 1
        fi

  splitter2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ startsWith(github.event.comment.body, '/add-labels') }}
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            documentation
            changelog
